export enum ItemType {
  Text              = 'text',
  Select            = 'select',
  Range             = 'range',
  Date              = 'date',
  DateTime          = 'datetime',
  DateRange         = 'daterange',
  Week              = 'week',
  DateTimeRange     = 'datetimerange',
  MonthRange        = 'monthrange',
  AutoComplete      = 'autocomplete',
  AutoCompleteChips = 'autocompletechips',
  Checkbox          = 'checkbox',
  Chips             = 'chips',
  Keyword           = 'keyword',
}
